headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "ui"
package = "@netlify/plugin-lighthouse"

[plugins.inputs]

[build]
publish = "/home/ubuntu/STRIPE_ULTRATHINK_PROJECT/landing-site/landing-site"
publishOrigin = "config"
base = "/home/ubuntu/STRIPE_ULTRATHINK_PROJECT/landing-site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]